### PR TITLE
Fix Anniversary Update regression

### LINKED ISSUE #5: Can't view starting items after aniversery update
As title says, anniversary update shows a blank screen when trying to view starting items.

### PR DESCRIPTION
**Pull request by IsmetBesic**
There seems to have been a field name change - identified by reviewing the new method name with dnSpy and testing / confirming the change to work locally. 

This seemingly fixes https://github.com/Phedg1Studios/StartingItemsGUI/issues/5.

### CODE REVIEW

**Comment by Indra-db** [comment]
@IsmetBesic any chance you can make a compiled version out of this to share? I tried compiling it myself with the fix, but I couldn't figure it. 

If possible, I could get it from your github if you upload it there or you can send me at xxx (removed the email address since I received it)

**Comment by Indra-db** [comment]
@IsmetBesic Got it, thanks thanks and another thanks :D.

**Comment by KombiKiori** [comment]
@IsmetBesic can I also get compiled version pretty please?

I also leave email then. ( remove it cuz have response )
sorry for disturb you.

**Comment by IsmetBesic** [comment]
I have gone ahead and published an updated compiled version as a [release](https://github.com/IsmetBesic/StartingItemsGUI/releases) inside the forked repository.

**Comment by KingTate** [comment]
i have changed the file and the menu now works but cant earn credits from a run.

**Comment by KingTate** [comment]
@IsmetBesic is it possible get another fix for this mod due to the patch that came out on Monday April 12th? the mod loads but I cant see anything in the main menu screen for selecting starting items
error

**Comment by IsmetBesic** [comment]
Since Phedg1Studios has come around to officially updating the mod, I will close this PR - thank you very much, @Phedg1Studios. 

(The dictionary-related issue unfortunately exceeded my limited debugging capabilities w.r.t. Unity)

**Pull request closed without merging**
